version: '3.5'

networks:
  rmoff_kafka:
    name: rmoff_kafka

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    networks:
      - rmoff_kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker
    ports:
      - "19092:19092"
    networks:
      - rmoff_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,CONNECTIONS_FROM_HOST://172.25.135.222:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  client-consumer:
    build: ./kafka-consumer
    container_name: kafka-consumer
    depends_on:
      - broker
      - zookeeper
    networks:
      - rmoff_kafka
    environment:
      CLIENT_ID: 1

  client-producer:
    build: ./kafka-producer
    container_name: kafka-producer
    ports:
      - "8083:8083"
    depends_on:
      - broker
      - zookeeper
    networks:
      - rmoff_kafka

  client-producer-2types:
    build: ./kafka-producer-two-types
    container_name: kafka-producer-two-types
    ports:
      - "8090:8090"
    depends_on:
      - broker
      - zookeeper
    networks:
      - rmoff_kafka
