spring:
  kafka:
    ssl:
      key-store-location: file:/certs/kafka.client.keystore.jks
      key-store-password: Venick
      trust-store-location:  file:/certs/kafka.client.truststore.jks
      trust-store-password: Venick
      key-password: Venick
    properties:
      security.protocol: "SSL"
#    bootstrap-servers: broker:9092
#    consumer:
#      bootstrap-servers: broker:9092
#      group-id: demo-group-id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: broker:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
