version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092, SSL://broker:9092
      KAFKA_LISTENERS: PLAINTEXT://localhost:29092, SSL://broker:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL

      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore_creds

      KAFKA_SECURITY_PROTOCOL: 'SSL'
      KAFKA_SSL_CLIENT_AUTH: 'required'
#      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'SSL'
#      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
    volumes:
      - /mnt/d/training/projects/kafka-my-projects/kafka-training-project/kafka-producer-ssl/certs:/etc/kafka/secrets

